### ISSUE TITLE
mobile site ummm

### ISSUE THREAD

**Issue by atpage** [BSidesROC/BSidesROC.github.io#36]
Is this what we're going with?

![Screenshot_20200218-134431](https://user-images.githubusercontent.com/4260357/74767688-516cbd00-5255-11ea-99ec-7067db285b3c.png)

**Comment by spark0r** [comment]
I would welcome any PR that further refined the layouts ( beyond Bootstrap defaults ) for phone / tablet. This page https://jekyllrb.com/docs/ walks you through the basics of how to get things setup to generate / view the site locally and here's the css framework that's being used: https://getbootstrap.com/docs/4.4/getting-started/introduction/

**Comment by spark0r** [comment]
resolved in: https://github.com/BSidesROC/BSidesROC.github.io/pull/38
